#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/dave/gams/installation/MPC/mwc.pl -type make -features vrep=0,tests=0,docs=1 workspace.mwc
#
#----------------------------------------------------------------------------


all: custom_controller documentation_custom

depend: custom_controller-depend documentation_custom-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.custom_controller $(@)
	@cd docs && $(MAKE) -f Makefile.documentation_custom $(@)

.PHONY: custom_controller
custom_controller:
	@$(MAKE) -f Makefile.custom_controller all

.PHONY: custom_controller-depend
custom_controller-depend:
	@$(MAKE) -f Makefile.custom_controller depend

.PHONY: documentation_custom
documentation_custom:
	@cd docs && $(MAKE) -f Makefile.documentation_custom all

.PHONY: documentation_custom-depend
documentation_custom-depend:
	@cd docs && $(MAKE) -f Makefile.documentation_custom depend

project_name_list:
	@echo custom_controller
	@echo documentation_custom
