
#ifndef   _THREAD_CONSUMER_H_
#define   _THREAD_CONSUMER_H_

#include <string>

#include "madara/threads/BaseThread.h"
#include "madara/knowledge/containers/Integer.h"

namespace knowledge = madara::knowledge;
namespace containers = knowledge::containers;

namespace threads
{
  /**
  * A custom thread generated by gpc.pl
  **/
  class consumer : public madara::threads::BaseThread
  {
  public:
    /**
     * Default constructor
     **/
    consumer ();
    
    /**
     * Destructor
     **/
    virtual ~consumer ();
    
    /**
      * Initializes thread with MADARA context
      * @param   context   context for querying current program state
      **/
    virtual void init (madara::knowledge::KnowledgeBase & knowledge);

    /**
      * Executes the main thread logic
      **/
    virtual void run (void);

  private:
    /// data plane if we want to access the knowledge base
    madara::knowledge::KnowledgeBase data_;

    /// iterations between writing to file
    int write_out_interval = 5;
  };
} // end namespace threads

#endif // _THREAD_CONSUMER_H_
