
#ifndef   _THREAD_PRODUCER_H_
#define   _THREAD_PRODUCER_H_

#include <string>

#include "madara/threads/BaseThread.h"
#include "madara/knowledge/containers/Integer.h"

namespace knowledge = madara::knowledge;
namespace containers = knowledge::containers;

namespace threads
{
  /**
  * A custom thread generated by gpc.pl
  **/
  class producer : public madara::threads::BaseThread
  {
  public:
    /**
     * Default constructor
     **/
    producer ();
    
    /**
     * Destructor
     **/
    virtual ~producer ();
    
    /**
      * Initializes thread with MADARA context
      * @param   context   context for querying current program state
      **/
    virtual void init (madara::knowledge::KnowledgeBase & knowledge);

    /**
      * Executes the main thread logic
      **/
    virtual void run (void);

  private:
    /// data plane if we want to access the knowledge base
    madara::knowledge::KnowledgeBase data_;

  protected:
    // a place to stash our produced random integer
    containers::Integer random_number;

  };
} // end namespace threads

#endif // _THREAD_PRODUCER_H_
